DROP TABLE RentedBook;
DROP SEQUENCE SEQ_rentedBookID;
SELECT * FROM RentedBook;

DROP TABLE copyOfBook;
DROP SEQUENCE SEQ_copyOfBookID;
SELECT * FROM copyOfBook;

DROP TABLE LIBRARY;
DROP SEQUENCE SEQ_LibraryID;
SELECT * FROM Library;

DROP TABLE Book;
DROP SEQUENCE SEQ_BookID;
SELECT * FROM Book;

DROP TABLE Visitor;
DROP SEQUENCE SEQ_VisitorID;
SELECT * FROM Visitor;